name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: 3.10

      - name: Setup Cog
        uses: replicate/setup-cog@v1
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      - name: Cog predict
        run: cog predict -i text='i am a boy that fucks'

      - name: Install replicate
        run: pip install replicate
        

      - name: Push to Replicate
        run: |
          cog push r8.im/damilojohn/gpt2-small
        env:
          token: ${{ secrets.REPLICATE_API_TOKEN }}